security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
            my_ldap:
                ldap:
                    service: Symfony\Component\Ldap\Ldap
                    base_dn: dc=KP,dc=local
                    search_dn: "cn=testas testas,cn=Users,dc=KP,dc=local"
                    search_password: ZXCvbn123++
                    default_roles: ROLE_USER
                    uid_key: sAMAccountName

    firewalls:
        main:
            form_login_ldap:
                            service: Symfony\Component\Ldap\Ldap
                            dn_string: 'dc=KP,dc=local'
                            query_string: '(&(objectCategory=person)(objectclass=User)(sAMAccountName={username}))'
                            login_path: login
                            check_path: login
                            failure_path: login
                            default_target_path: main

            logout:
                  path: logout
                  target: main
            anonymous:    ~

    access_control:
        # require ROLE_ADMIN for /admin*
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
         - { path: ^/, roles: ROLE_USER }
         - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #(memberOf=CN=ADMD.admins,OU=Administration Accounts,DC=DAIS,DC=local)



